version: '3.8'

services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./packages/backend:/app
      - /app/venv
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - kevin-network

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - backend
    networks:
      - kevin-network

networks:
  kevin-network:
    driver: bridge

volumes:
  backend_data:
  frontend_data:

