name: Linting Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
      
      - name: Run linting checks
        run: |
          echo "🔍 Running linting checks..."
          echo "❌ CRITICAL: Code style violations detected!"
          echo "   - Line too long in main.py:42"
          echo "   - Missing docstring in game/player.py"
          echo "   - Unused import in utils/save_load.py"
          echo "   - Inconsistent indentation in locations/forest.py"
          echo ""
          echo "💥 Linting check failed with 4 violations"
          exit 1
