name: Failing Check 2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  failing-job:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Wait for 1 minute then fail
      run: |
        echo "Starting failing check..."
        echo "This check will run for 1 minute and then fail"
        
        # Wait for 60 seconds (1 minute)
        sleep 60
        
        echo "1 minute has passed, now failing..."
        exit 1
